// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenTelemetryDashboard.Persistence;

#nullable disable

namespace OpenTelemetryDashboard.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<string>("Body")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<uint>("DroppedAttributesCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flags");

                    b.Property<long>("ObservedTimeUnixNano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_time_unix_nano");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_version");

                    b.Property<int>("SeverityNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("severity_number");

                    b.Property<string>("SeverityText")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity_text");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .HasColumnName("span_id");

                    b.Property<long>("TimeUnixNano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_unix_nano");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_records");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_log_records_resource_hash");

                    b.HasIndex("SeverityNumber")
                        .HasDatabaseName("ix_log_records_severity_number");

                    b.HasIndex("TimeUnixNano")
                        .HasDatabaseName("ix_log_records_time_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_log_records_trace_id");

                    b.ToTable("log_records", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Resource", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("hash");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<uint>("DroppedAttributesCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<string>("SchemaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_url");

                    b.Property<string>("ServiceInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_instance_id");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.HasKey("Hash")
                        .HasName("pk_resources");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_resources_service_name");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<uint>("DroppedAttributesCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<uint>("DroppedEventsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped_events_count");

                    b.Property<uint>("DroppedLinksCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dropped_links_count");

                    b.Property<long>("EndUnixNano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_unix_nano");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flags");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("ParentSpanId")
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .HasColumnName("parent_span_id");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_version");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("BLOB")
                        .HasColumnName("span_id");

                    b.Property<long>("StartUnixNano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_unix_nano");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("status_message");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_spans");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_spans_resource_hash");

                    b.HasIndex("StartUnixNano")
                        .HasDatabaseName("ix_spans_start_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_spans_trace_id");

                    b.ToTable("spans", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_records_resources_resource_hash");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spans_resources_resource_hash");

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanEvent", "Events", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("attributes");

                            b1.Property<uint>("DroppedAttributesCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("owner_span_id");

                            b1.Property<long>("TimeUnixNano")
                                .HasColumnType("INTEGER")
                                .HasColumnName("time_unix_nano");

                            b1.HasKey("Id")
                                .HasName("pk_span_events");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_events_owner_span_id");

                            b1.ToTable("span_events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_events_spans_owner_span_id");
                        });

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanLink", "Links", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("attributes");

                            b1.Property<uint>("DroppedAttributesCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<uint>("Flags")
                                .HasColumnType("INTEGER")
                                .HasColumnName("flags");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("owner_span_id");

                            b1.Property<byte[]>("SpanId")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("BLOB")
                                .HasColumnName("linked_span_id");

                            b1.Property<byte[]>("TraceId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("BLOB")
                                .HasColumnName("linked_trace_id");

                            b1.HasKey("Id")
                                .HasName("pk_span_links");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_links_owner_span_id");

                            b1.ToTable("span_links", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_links_spans_owner_span_id");
                        });

                    b.Navigation("Events");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
