// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenTelemetryDashboard.Persistence;

#nullable disable

namespace OpenTelemetryDashboard.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260430172516_RemoveDefaultDashboardSeed")]
    partial class RemoveDefaultDashboardSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<string>("Body")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<long>("ObservedTimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_time_unix_nano");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("scope_version");

                    b.Property<int>("SeverityNumber")
                        .HasColumnType("int")
                        .HasColumnName("severity_number");

                    b.Property<string>("SeverityText")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("severity_text");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)")
                        .HasColumnName("span_id");

                    b.Property<long>("TimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("time_unix_nano");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_records");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_log_records_resource_hash");

                    b.HasIndex("SeverityNumber")
                        .HasDatabaseName("ix_log_records_severity_number");

                    b.HasIndex("TimeUnixNano")
                        .HasDatabaseName("ix_log_records_time_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_log_records_trace_id");

                    b.ToTable("log_records", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Resource", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("hash");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<string>("SchemaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("schema_url");

                    b.Property<string>("ServiceInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("service_instance_id");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("service_name");

                    b.HasKey("Hash")
                        .HasName("pk_resources");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_resources_service_name");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<long>("DroppedEventsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_events_count");

                    b.Property<long>("DroppedLinksCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_links_count");

                    b.Property<long>("EndUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("end_unix_nano");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ParentSpanId")
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)")
                        .HasColumnName("parent_span_id");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("scope_version");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)")
                        .HasColumnName("span_id");

                    b.Property<long>("StartUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("start_unix_nano");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("status_message");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_spans");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_spans_resource_hash");

                    b.HasIndex("StartUnixNano")
                        .HasDatabaseName("ix_spans_start_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_spans_trace_id");

                    b.ToTable("spans", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dashboards");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_json");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dashboard_id");

                    b.Property<int>("H")
                        .HasColumnType("int")
                        .HasColumnName("h");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("kind");

                    b.Property<int>("W")
                        .HasColumnType("int")
                        .HasColumnName("w");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_widgets");

                    b.HasIndex("DashboardId")
                        .HasDatabaseName("ix_dashboard_widgets_dashboard_id");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.WidgetDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BaseKind")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("base_kind");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_json");

                    b.Property<int>("DefaultH")
                        .HasColumnType("int")
                        .HasColumnName("default_h");

                    b.Property<int>("DefaultW")
                        .HasColumnType("int")
                        .HasColumnName("default_w");

                    b.Property<string>("Description")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)")
                        .HasColumnName("description");

                    b.Property<int>("Engine")
                        .HasColumnType("int")
                        .HasColumnName("engine");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SpecJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spec_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_widget_definitions");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_widget_definitions_updated_at");

                    b.ToTable("widget_definitions", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMonotonic")
                        .HasColumnType("bit")
                        .HasColumnName("is_monotonic");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("scope_version");

                    b.Property<int>("Temporality")
                        .HasColumnType("int")
                        .HasColumnName("temporality");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_instruments_resource_hash");

                    b.HasIndex("ResourceHash", "ScopeName", "Name", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_resource_hash_scope_name_name_kind");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.MetricPointRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<long>("StartTimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time_unix_nano");

                    b.Property<long>("TimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("time_unix_nano");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_metric_points");

                    b.HasIndex("TimeUnixNano")
                        .HasDatabaseName("ix_metric_points_time_unix_nano");

                    b.HasIndex("InstrumentId", "TimeUnixNano")
                        .HasDatabaseName("ix_metric_points_instrument_id_time_unix_nano");

                    b.ToTable("metric_points", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_records_resources_resource_hash");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spans_resources_resource_hash");

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanEvent", "Events", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("attributes");

                            b1.Property<long>("DroppedAttributesCount")
                                .HasColumnType("bigint")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("name");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_span_id");

                            b1.Property<long>("TimeUnixNano")
                                .HasColumnType("bigint")
                                .HasColumnName("time_unix_nano");

                            b1.HasKey("Id")
                                .HasName("pk_span_events");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_events_owner_span_id");

                            b1.ToTable("span_events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_events_spans_owner_span_id");
                        });

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanLink", "Links", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("attributes");

                            b1.Property<long>("DroppedAttributesCount")
                                .HasColumnType("bigint")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<long>("Flags")
                                .HasColumnType("bigint")
                                .HasColumnName("flags");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_span_id");

                            b1.Property<byte[]>("SpanId")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varbinary(8)")
                                .HasColumnName("linked_span_id");

                            b1.Property<byte[]>("TraceId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("varbinary(16)")
                                .HasColumnName("linked_trace_id");

                            b1.HasKey("Id")
                                .HasName("pk_span_links");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_links_owner_span_id");

                            b1.ToTable("span_links", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_links_spans_owner_span_id");
                        });

                    b.Navigation("Events");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.DashboardWidget", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widgets_dashboards_dashboard_id");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_resources_resource_hash");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.MetricPointRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metric_points_instruments_instrument_id");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
