// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenTelemetryDashboard.Persistence;

#nullable disable

namespace OpenTelemetryDashboard.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260429205215_SeedDefaultDashboard")]
    partial class SeedDefaultDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("Body")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("body");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<long>("ObservedTimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_time_unix_nano");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_version");

                    b.Property<int>("SeverityNumber")
                        .HasColumnType("integer")
                        .HasColumnName("severity_number");

                    b.Property<string>("SeverityText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("severity_text");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasColumnName("span_id");

                    b.Property<long>("TimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("time_unix_nano");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_records");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_log_records_resource_hash");

                    b.HasIndex("SeverityNumber")
                        .HasDatabaseName("ix_log_records_severity_number");

                    b.HasIndex("TimeUnixNano")
                        .HasDatabaseName("ix_log_records_time_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_log_records_trace_id");

                    b.ToTable("log_records", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Resource", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<string>("SchemaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("schema_url");

                    b.Property<string>("ServiceInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_instance_id");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.HasKey("Hash")
                        .HasName("pk_resources");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_resources_service_name");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<long>("DroppedAttributesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_attributes_count");

                    b.Property<long>("DroppedEventsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_events_count");

                    b.Property<long>("DroppedLinksCount")
                        .HasColumnType("bigint")
                        .HasColumnName("dropped_links_count");

                    b.Property<long>("EndUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("end_unix_nano");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ParentSpanId")
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasColumnName("parent_span_id");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_version");

                    b.Property<byte[]>("SpanId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasColumnName("span_id");

                    b.Property<long>("StartUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("start_unix_nano");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("status_message");

                    b.Property<byte[]>("TraceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_spans");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_spans_resource_hash");

                    b.HasIndex("StartUnixNano")
                        .HasDatabaseName("ix_spans_start_unix_nano");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_spans_trace_id");

                    b.ToTable("spans", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dashboards");

                    b.ToTable("dashboards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "main",
                            RowVersion = 0L,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<int>("H")
                        .HasColumnType("integer")
                        .HasColumnName("h");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<int>("W")
                        .HasColumnType("integer")
                        .HasColumnName("w");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_widgets");

                    b.HasIndex("DashboardId")
                        .HasDatabaseName("ix_dashboard_widgets_dashboard_id");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMonotonic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monotonic");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ResourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("resource_hash");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scope_name");

                    b.Property<string>("ScopeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_version");

                    b.Property<int>("Temporality")
                        .HasColumnType("integer")
                        .HasColumnName("temporality");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("ResourceHash")
                        .HasDatabaseName("ix_instruments_resource_hash");

                    b.HasIndex("ResourceHash", "ScopeName", "Name", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_resource_hash_scope_name_name_kind");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.MetricPointRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<long>("StartTimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time_unix_nano");

                    b.Property<long>("TimeUnixNano")
                        .HasColumnType("bigint")
                        .HasColumnName("time_unix_nano");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_metric_points");

                    b.HasIndex("TimeUnixNano")
                        .HasDatabaseName("ix_metric_points_time_unix_nano");

                    b.HasIndex("InstrumentId", "TimeUnixNano")
                        .HasDatabaseName("ix_metric_points_instrument_id_time_unix_nano");

                    b.ToTable("metric_points", (string)null);
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.LogRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_records_resources_resource_hash");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Core.Domain.Span", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spans_resources_resource_hash");

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanEvent", "Events", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("attributes");

                            b1.Property<long>("DroppedAttributesCount")
                                .HasColumnType("bigint")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("name");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_span_id");

                            b1.Property<long>("TimeUnixNano")
                                .HasColumnType("bigint")
                                .HasColumnName("time_unix_nano");

                            b1.HasKey("Id")
                                .HasName("pk_span_events");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_events_owner_span_id");

                            b1.ToTable("span_events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_events_spans_owner_span_id");
                        });

                    b.OwnsMany("OpenTelemetryDashboard.Core.Domain.SpanLink", "Links", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("attributes");

                            b1.Property<long>("DroppedAttributesCount")
                                .HasColumnType("bigint")
                                .HasColumnName("dropped_attributes_count");

                            b1.Property<long>("Flags")
                                .HasColumnType("bigint")
                                .HasColumnName("flags");

                            b1.Property<long>("OwnerSpanId")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_span_id");

                            b1.Property<byte[]>("SpanId")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("bytea")
                                .HasColumnName("linked_span_id");

                            b1.Property<byte[]>("TraceId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("bytea")
                                .HasColumnName("linked_trace_id");

                            b1.HasKey("Id")
                                .HasName("pk_span_links");

                            b1.HasIndex("OwnerSpanId")
                                .HasDatabaseName("ix_span_links_owner_span_id");

                            b1.ToTable("span_links", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OwnerSpanId")
                                .HasConstraintName("fk_span_links_spans_owner_span_id");
                        });

                    b.Navigation("Events");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.DashboardWidget", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", null)
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_widgets_dashboards_dashboard_id");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Core.Domain.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourceHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_resources_resource_hash");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Persistence.Metrics.Entities.MetricPointRecord", b =>
                {
                    b.HasOne("OpenTelemetryDashboard.Persistence.Metrics.Entities.InstrumentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metric_points_instruments_instrument_id");
                });

            modelBuilder.Entity("OpenTelemetryDashboard.Dashboards.Domain.Dashboard", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
